### ISSUE TITLE
Chat messages from my plugin unable to show on demos.tf

### ISSUE THREAD

**Issue by blakeplusplus** [demostf/frontend#1]
### Context

I have a SourceMod [plugin](https://github.com/blakeplusplus/p4sstime) that's used for the 4v4 PASS Time gamemode which is going to be played in the upcoming RGL cup. I'm trying to add prints that print only to the STV client that show when events happen, so players who are looking to create fragmovies can have an easier time locating certain game events by simply looking at the chat for the demo in their browser. I've gotten that working and confirmed by looking in the STV demo itself. Example here: https://demos.tf/1115085

![example](https://github.com/demostf/frontend/assets/76140847/ce7b14c3-aace-42c8-a0c0-3c83035865ca)
First print is to all clients, second print is only to STV.

### Issue

Since the prints to STV from my plugin are not showing up, I am assuming that there is some sort of filter in place. Is that true, or is there some sort of issue with my plugin I need to resolve?

Thanks

**Comment by icewind1991** [comment]
Fixed with https://github.com/demostf/parser/commit/217211f2fb25cf66edc7f9e70be1322e7b05a59a
